// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateBlog(ctx context.Context, arg CreateBlogParams) (Blog, error)
	CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error)
	CreateFavorite(ctx context.Context, blogID uuid.UUID) (Favorite, error)
	DeleteBlog(ctx context.Context, id uuid.UUID) error
	DeleteComment(ctx context.Context, id uuid.UUID) error
	DeleteFavorite(ctx context.Context, id uuid.UUID) error
	GetBlog(ctx context.Context, id uuid.UUID) (Blog, error)
	GetBlogBySlug(ctx context.Context, slug string) (Blog, error)
	GetComment(ctx context.Context, id uuid.UUID) (Comment, error)
	GetFavorite(ctx context.Context, id uuid.UUID) (Favorite, error)
	ListBlogs(ctx context.Context, arg ListBlogsParams) ([]Blog, error)
	ListCommentsByBlog(ctx context.Context, arg ListCommentsByBlogParams) ([]Comment, error)
	ListFavoritesByBlog(ctx context.Context, arg ListFavoritesByBlogParams) ([]Favorite, error)
	UpdateBlog(ctx context.Context, arg UpdateBlogParams) (Blog, error)
	UpdateComment(ctx context.Context, arg UpdateCommentParams) (Comment, error)
}

var _ Querier = (*Queries)(nil)
